version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: shardendu1234
      POSTGRES_PASSWORD: shardendu1234
      POSTGRES_DB: shardendu1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}